# Generated by Django 3.2.6 on 2025-07-15 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(max_length=5, verbose_name='ประเภท')),
                ('asset_kind', models.CharField(max_length=5, verbose_name='ชนิด')),
                ('asset_character', models.CharField(max_length=5, verbose_name='ลักษณะ')),
                ('serial_year', models.CharField(max_length=10, verbose_name='ลำดับ/ปี')),
            ],
            options={
                'unique_together': {('asset_type', 'asset_kind', 'asset_character', 'serial_year')},
            },
        ),
        migrations.CreateModel(
            name='AssetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='ชื่อรายการครุภัณฑ์')),
                ('quantity', models.IntegerField(verbose_name='จำนวน')),
                ('unit', models.CharField(max_length=50, verbose_name='หน่วยนับ')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาที่ซื้อ')),
                ('purchase_date', models.DateField(verbose_name='วันที่ซื้อ')),
                ('fiscal_year', models.IntegerField(verbose_name='ปีที่ใช้งาน')),
                ('lifetime', models.IntegerField(verbose_name='อายุการใช้งาน (ปี)')),
                ('used_years', models.IntegerField(verbose_name='ใช้มาแล้วกี่ปี')),
                ('annual_depreciation', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ค่าความเสื่อมต่อปี')),
                ('responsible_person', models.CharField(max_length=255, verbose_name='ผู้รับผิดชอบดูแลกำกับ')),
                ('brand_model', models.CharField(max_length=255, verbose_name='ยี่ห้อ/รุ่น')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('damage_status', models.CharField(choices=[('ชำรุด', 'ชำรุด'), ('เสื่อม', 'เสื่อม'), ('สูญไป', 'สูญไป'), ('ไม่ใช้', 'ไม่ใช้'), ('ใช้อยู่', 'ใช้อยู่')], max_length=10, verbose_name='สถานะการใช้งาน')),
                ('status_borrowing', models.BooleanField(default=False, verbose_name='ครุภัณฑ์ที่ยืมได้')),
                ('status_assetloan', models.BooleanField(default=False, verbose_name='สถานะการยืม')),
                ('asset_image', models.ImageField(blank=True, null=True, upload_to='assets/', verbose_name='รูปภาพครุภัณฑ์')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='QR Code')),
                ('asset_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetcode', verbose_name='รหัสครุภัณฑ์')),
            ],
            options={
                'verbose_name': 'ครุภัณฑ์',
                'verbose_name_plural': 'รายการครุภัณฑ์',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cate', models.CharField(max_length=100, verbose_name='หมวดหมู่หลัก')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='สถานที่เก็บ')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sub', models.CharField(max_length=100, verbose_name='หมวดหมู่ย่อย')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='assets.category', verbose_name='หมวดหมู่หลัก')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AssetOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มครอบครอง')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดการครอบครอง')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetitem', verbose_name='ครุภัณฑ์')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ครอบครอง')),
            ],
        ),
        migrations.CreateModel(
            name='AssetLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateField(auto_now_add=True, verbose_name='วันที่ยืม')),
                ('date_of_use', models.DateField(blank=True, null=True, verbose_name='วันที่ใช้')),
                ('date_of_return', models.DateField(blank=True, null=True, verbose_name='วันที่คืน')),
                ('date_due', models.DateField(verbose_name='กำหนดคืน')),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('borrowed', 'กำลังยืม'), ('returned_pending', 'รออนุมัติการคืน'), ('returned', 'คืนแล้ว'), ('overdue', 'เกินกำหนด')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('date_received', models.DateTimeField(blank=True, null=True, verbose_name='วันที่รับ')),
                ('confirm', models.BooleanField(default=False, verbose_name='ยืนยันรับครุภัณฑ์')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetitem', verbose_name='ครุภัณฑ์ที่ยืม')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืม')),
            ],
        ),
        migrations.AddField(
            model_name='assetitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subcategory', to='assets.subcategory', verbose_name='หมวดหมู่'),
        ),
        migrations.AddField(
            model_name='assetitem',
            name='storage_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.storagelocation', verbose_name='สถานที่เก็บ'),
        ),
        migrations.CreateModel(
            name='AssetCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(auto_now_add=True, verbose_name='วันที่ตรวจเช็ค')),
                ('status', models.BooleanField(default=False, verbose_name='สถานะการตรวจเช็ค')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='หมายเหตุเพิ่มเติม')),
                ('month', models.PositiveIntegerField(editable=False, verbose_name='เดือนที่บันทึก')),
                ('year', models.PositiveIntegerField(editable=False, verbose_name='ปีงบประมาณ')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetitem', verbose_name='ครุภัณฑ์ที่ตรวจเช็ค')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้ตรวจเช็ค')),
            ],
        ),
    ]
