# Generated by Django 3.2.6 on 2025-08-08 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_assetitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_items', to='assets.subcategory', verbose_name='หมวดหมู่'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='assets.category', verbose_name='หมวดหมู่หลัก'),
        ),
    ]
