# Generated by Django 3.2.6 on 2025-08-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_auto_20250808_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetitem',
            old_name='category',
            new_name='subcategory',
        ),
    ]
