# Generated by Django 3.2.6 on 2025-08-14 04:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_category_assetitem_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='assetitem',
            name='date_asset_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 8, 14, 4, 15, 46, 462036, tzinfo=utc), verbose_name='วันที่เพิ่มข้อมูล'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assetitem',
            name='date_asset_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดทข้อมูล'),
        ),
    ]
