# Generated by Django 3.2.6 on 2025-08-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_auto_20250814_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcode',
            name='serial_year',
            field=models.CharField(max_length=10, unique=True, verbose_name='ลำดับ/ปี'),
        ),
        migrations.AlterUniqueTogether(
            name='assetcode',
            unique_together=set(),
        ),
    ]
