# Generated by Django 3.2.6 on 2025-08-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20250814_1533'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='AssetCategory',
        ),
    ]
