# Generated by Django 3.2.6 on 2025-08-25 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0007_rename_category_assetcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuingAssetLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ทำรายการ')),
                ('month', models.PositiveIntegerField(default=8, editable=False, verbose_name='เดือน')),
                ('year', models.PositiveIntegerField(default=2025, editable=False, verbose_name='ปี')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_loans', to='assets.assetitem', verbose_name='ครุภัณฑ์ที่ยืม')),
            ],
        ),
        migrations.CreateModel(
            name='OrderAssetLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้างออเดอร์')),
                ('date_of_use', models.DateField(blank=True, null=True, verbose_name='วันที่ใช้')),
                ('date_due', models.DateField(verbose_name='กำหนดคืน')),
                ('date_of_return', models.DateField(blank=True, null=True, verbose_name='วันที่คืนจริง')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='อัพเดทล่าสุด')),
                ('status', models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('borrowed', 'กำลังยืม'), ('returned_pending', 'รออนุมัติการคืน'), ('returned', 'คืนแล้ว'), ('overdue', 'เกินกำหนด')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อเจ้าหน้าที่อนุมัติ')),
                ('approver_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่งเจ้าหน้าที่อนุมัติ')),
                ('date_approved', models.DateField(blank=True, null=True, verbose_name='วันที่อนุมัติ')),
                ('returned_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อผู้คืนครุภัณฑ์')),
                ('date_returned', models.DateField(blank=True, null=True, verbose_name='วันที่คืน')),
                ('received_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อเจ้าหน้าที่รับคืน')),
                ('receiver_position', models.CharField(blank=True, max_length=100, null=True, verbose_name='ตำแหน่งเจ้าหน้าที่รับคืน')),
                ('confirm_received', models.BooleanField(default=False, verbose_name='ยืนยันการรับคืน')),
                ('receiver_note', models.TextField(blank=True, null=True, verbose_name='ความคิดเห็นเจ้าหน้าที่รับคืน')),
                ('date_received', models.DateField(blank=True, null=True, verbose_name='วันที่บันทึกรับคืน')),
                ('month', models.PositiveIntegerField(default=8, editable=False, verbose_name='เดือน')),
                ('year', models.PositiveIntegerField(default=2025, editable=False, verbose_name='ปี')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_loans', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ยืมครุภัณฑ์')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.DeleteModel(
            name='AssetLoan',
        ),
        migrations.AddField(
            model_name='issuingassetloan',
            name='order_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assets.orderassetloan', verbose_name='ออเดอร์'),
        ),
    ]
