# Generated by Django 3.2 on 2025-09-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20250825_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetitem',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='issuingassetloan',
            name='month',
            field=models.PositiveIntegerField(default=9, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='month',
            field=models.PositiveIntegerField(default=9, editable=False, verbose_name='เดือน'),
        ),
    ]
