# Generated by Django 3.2.6 on 2025-09-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_auto_20250901_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderassetloan',
            name='status_return',
            field=models.CharField(choices=[('damaged', 'ชำรุด'), ('not_damaged', 'ไม่มีรายการชำรุด')], default='not_damaged', max_length=20, verbose_name='สถานะการคืน'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('borrowed', 'กำลังยืม'), ('returned_pending', 'รออนุมัติการคืน'), ('returned', 'คืนแล้ว'), ('overdue', 'เกินกำหนด')], default='pending', max_length=20, verbose_name='สถานะการยืม'),
        ),
    ]
