# Generated by Django 3.2.6 on 2025-09-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_auto_20250902_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassetloan',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่อนุมัติ'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='date_due',
            field=models.DateTimeField(verbose_name='กำหนดคืน'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='date_of_return',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่คืนจริง'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='date_of_use',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ใช้'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่บันทึกรับคืน'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='date_returned',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่คืน'),
        ),
    ]
