# Generated by Django 3.2 on 2025-09-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_auto_20250903_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetItemLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255, verbose_name='ชื่อรายการครุภัณฑ์สำหรับยืม')),
                ('unit', models.CharField(max_length=50, verbose_name='หน่วยนับ')),
                ('brand_model', models.CharField(max_length=255, verbose_name='ยี่ห้อ/รุ่น')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('damage_status', models.CharField(choices=[('ชำรุด', 'ชำรุด'), ('เสื่อม', 'เสื่อม'), ('สูญไป', 'สูญไป'), ('ไม่ใช้', 'ไม่ใช้'), ('ใช้อยู่', 'ใช้อยู่')], max_length=10, verbose_name='สถานะการใช้งาน')),
                ('status_assetloan', models.BooleanField(default=False, verbose_name='สถานะการยืม')),
                ('status_borrowing', models.BooleanField(default=False, verbose_name='ครุภัณฑ์ที่ยืมได้')),
                ('asset_image', models.ImageField(blank=True, null=True, upload_to='assets_loan/', verbose_name='รูปภาพครุภัณฑ์')),
                ('asset_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetcode', verbose_name='รหัสครุภัณฑ์')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.storagelocation', verbose_name='สถานที่เก็บ')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_items_loan', to='assets.subcategory', verbose_name='หมวดหมู่')),
            ],
            options={
                'verbose_name': 'ครุภัณฑ์สำหรับยืม',
                'verbose_name_plural': 'รายการครุภัณฑ์สำหรับยืม',
            },
        ),
        migrations.AlterField(
            model_name='issuingassetloan',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_loans', to='assets.assetitemloan', verbose_name='ครุภัณฑ์ที่ยืม'),
        ),
    ]
