# Generated by Django 3.2 on 2025-09-09 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_auto_20250909_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetitemloan',
            name='asset_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสครุภัณฑ์'),
        ),
    ]
