# Generated by Django 3.2 on 2025-09-09 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0013_alter_assetitemloan_asset_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_date', models.DateTimeField(verbose_name='วัน/เวลาที่ต้องการยืม')),
                ('returning_date', models.DateTimeField(verbose_name='วัน/เวลาที่ต้องการคืน')),
                ('notes', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='วัน/เวลาที่จอง')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetitemloan', verbose_name='ครุภัณฑ์')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้จอง')),
            ],
            options={
                'verbose_name': 'การจองครุภัณฑ์',
                'verbose_name_plural': 'การจองครุภัณฑ์',
                'ordering': ['reserved_date'],
            },
        ),
    ]
