# Generated by Django 3.2 on 2025-09-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_assetreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassetloan',
            name='status',
            field=models.CharField(choices=[('pending', 'รออนุมัติ'), ('approved', 'อนุมัติแล้ว'), ('rejected', 'ปฏิเสธ'), ('borrowed', 'กำลังยืม'), ('returned_pending', 'รออนุมัติการคืน'), ('returned', 'คืนแล้ว'), ('overdue', 'เกินกำหนด'), ('cancel', 'ยกเลิกยืม')], default='pending', max_length=20, verbose_name='สถานะการยืม'),
        ),
    ]
