# Generated by Django 3.2 on 2025-09-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_alter_orderassetloan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassetloan',
            name='confirm_received',
            field=models.BooleanField(default=None, verbose_name='ยืนยันการรับคืน'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='status_return',
            field=models.CharField(choices=[('no', 'ยังไม่อนุมัติ'), ('damaged', 'ชำรุด'), ('not_damaged', 'ไม่มีรายการชำรุด')], default='no', max_length=20, verbose_name='สถานะการคืน'),
        ),
    ]
