# Generated by Django 3.2 on 2025-09-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_auto_20250911_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderassetloan',
            name='confirm_received',
            field=models.BooleanField(blank=True, default=None, null=True, verbose_name='ยืนยันการรับคืน'),
        ),
    ]
