# Generated by Django 3.2 on 2025-10-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_alter_orderassetloan_confirm_received'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetcategory',
            options={'ordering': ('-id',), 'verbose_name': 'หมวดหมู่หลักครุภัณฑ์'},
        ),
        migrations.AlterModelOptions(
            name='assetcheck',
            options={'ordering': ('-id',), 'verbose_name': 'ตารางตรวจเช็คครุภัณฑ์'},
        ),
        migrations.AlterModelOptions(
            name='assetcode',
            options={'ordering': ('-id',), 'verbose_name': 'รหัสครุภัณฑ์'},
        ),
        migrations.AlterModelOptions(
            name='assetownership',
            options={'ordering': ('-id',), 'verbose_name': 'ตารางการครอบครองครุภัณฑ์'},
        ),
        migrations.AlterModelOptions(
            name='issuingassetloan',
            options={'ordering': ('-id',), 'verbose_name': 'รายการในออเดอร์ที่ยืม'},
        ),
        migrations.AlterModelOptions(
            name='orderassetloan',
            options={'ordering': ('-id',), 'verbose_name': 'ออเดอร์การยืมทั้งหมด'},
        ),
        migrations.AlterModelOptions(
            name='storagelocation',
            options={'ordering': ('-id',), 'verbose_name': 'สถานที่เก็บรหัสครุภัณฑ์'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('-id',), 'verbose_name': 'หมวดหมู่ย่อยครุภัณฑ์'},
        ),
        migrations.AddField(
            model_name='orderassetloan',
            name='order_code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='รหัสออเดอร์'),
        ),
        migrations.AddField(
            model_name='orderassetloan',
            name='running_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='เลขลำดับ'),
        ),
        migrations.AlterField(
            model_name='issuingassetloan',
            name='month',
            field=models.PositiveIntegerField(default=10, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='month',
            field=models.PositiveIntegerField(default=10, editable=False, verbose_name='เดือน'),
        ),
    ]
