# Generated by Django 4.2.26 on 2026-06-09 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0019_alter_issuingassetloan_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetownership',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะครอบครองปัจจุบัน'),
        ),
        migrations.AlterField(
            model_name='assetitem',
            name='damage_status',
            field=models.CharField(choices=[('ใช้งานได้', 'ใช้งานได้'), ('ชำรุด', 'ชำรุด'), ('เสื่อมสภาพ', 'เสื่อมสภาพ'), ('สูญไป', 'สูญไป'), ('ไม่ใช้', 'ไม่ใช้')], max_length=15, verbose_name='สถานะการใช้งาน'),
        ),
        migrations.AlterField(
            model_name='assetownership',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='assets.assetitem', verbose_name='ครุภัณฑ์'),
        ),
        migrations.AlterField(
            model_name='issuingassetloan',
            name='month',
            field=models.PositiveIntegerField(default=6, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='issuingassetloan',
            name='year',
            field=models.PositiveIntegerField(default=2026, editable=False, verbose_name='ปี'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='month',
            field=models.PositiveIntegerField(default=6, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='year',
            field=models.PositiveIntegerField(default=2026, editable=False, verbose_name='ปี'),
        ),
        migrations.CreateModel(
            name='AssetTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ใบคำร้อง')),
                ('department_name', models.CharField(max_length=255, verbose_name='กลุ่ม/ฝ่าย ที่ยื่นคำร้อง')),
                ('status', models.CharField(choices=[('PENDING_HEAD', 'รอหัวหน้างานพัสดุเห็นชอบ'), ('PENDING_DIRECTOR', 'รอผู้อำนวยการอนุมัติ'), ('PENDING_ACTION', 'รอเจ้าหน้าที่พัสดุดำเนินการ'), ('COMPLETED', 'ดำเนินการเสร็จสิ้น'), ('REJECTED', 'ปฏิเสธ/ไม่อนุมัติ')], default='PENDING_HEAD', max_length=20, verbose_name='สถานะใบคำร้อง')),
                ('head_approved', models.BooleanField(blank=True, null=True, verbose_name='ความเห็นหัวหน้างาน (เห็นชอบ)')),
                ('head_reject_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลกรณีไม่เห็นชอบ')),
                ('head_action_date', models.DateField(blank=True, null=True, verbose_name='วันที่หัวหน้างานลงชื่อ')),
                ('director_approved', models.BooleanField(blank=True, null=True, verbose_name='การพิจารณาผู้อำนวยการ (อนุมัติ)')),
                ('director_reject_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลกรณีไม่อนุมัติ')),
                ('director_action_date', models.DateField(blank=True, null=True, verbose_name='วันที่ผู้อำนวยการลงชื่อ')),
                ('officer_action_status', models.CharField(blank=True, choices=[('MOVED', 'ดำเนินการเคลื่อนย้ายเสร็จสิ้น'), ('RETURNED', 'ดำเนินการส่งคืนผู้ควบคุมดูแลพัสดุเสร็จสิ้น'), ('FAILED', 'ไม่สามารถดำเนินการได้')], max_length=50, null=True, verbose_name='ผลการดำเนินการของเจ้าหน้าที่')),
                ('officer_fail_reason', models.TextField(blank=True, null=True, verbose_name='เหตุผลกรณีดำเนินการไม่ได้')),
                ('officer_action_date', models.DateField(blank=True, null=True, verbose_name='วันที่เจ้าหน้าที่ดำเนินการ')),
                ('director_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='director_approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้อำนวยการผู้ลงชื่อ')),
                ('head_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head_vetted_requests', to=settings.AUTH_USER_MODEL, verbose_name='หัวหน้างานพัสดุผู้ลงชื่อ')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_handled_requests', to=settings.AUTH_USER_MODEL, verbose_name='เจ้าหน้าที่พัสดุผู้ดำเนินการ')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_requests', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ขอเคลื่อนย้าย/ส่งคืน')),
            ],
            options={
                'verbose_name': 'ใบคำร้องขอเคลื่อนย้าย/ส่งคืนครุภัณฑ์',
                'verbose_name_plural': 'ใบคำร้องขอเคลื่อนย้าย/ส่งคืนครุภัณฑ์',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='AssetTransferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('MOVE', 'เคลื่อนย้าย'), ('RETURN', 'ส่งคืน')], max_length=10, verbose_name='ความประสงค์')),
                ('condition', models.CharField(choices=[('ใช้งานได้', 'ใช้งานได้'), ('ชำรุด', 'ชำรุด'), ('เสื่อมสภาพ', 'เสื่อมสภาพ')], max_length=15, verbose_name='สภาพการใช้งาน ณ วันที่ขอ')),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='หมายเหตุ (การเคลื่อนย้าย)')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.assetitem', verbose_name='ครุภัณฑ์')),
                ('request_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='assets.assettransferrequest', verbose_name='ใบคำร้อง')),
                ('transfer_from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_moved_from', to='assets.storagelocation', verbose_name='ดำเนินการเคลื่อนย้ายจาก')),
                ('transfer_to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_moved_to', to='assets.storagelocation', verbose_name='ไปยัง / ส่งคืนที่')),
            ],
            options={
                'verbose_name': 'รายการครุภัณฑ์ในใบคำร้อง',
                'verbose_name_plural': 'รายการครุภัณฑ์ในใบคำร้อง',
            },
        ),
    ]
