# Generated by Django 4.2.26 on 2026-06-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_assetownership_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assettransferrequest',
            name='request_code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='เลขที่ใบคำร้อง'),
        ),
        migrations.AddField(
            model_name='assettransferrequest',
            name='running_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='เลขลำดับ'),
        ),
        migrations.AddField(
            model_name='assettransferrequest',
            name='year',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='ปี'),
        ),
    ]
