# Generated by Django 4.2.16 on 2026-08-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_assettransferrequest_request_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcheck',
            name='month',
        ),
        migrations.RemoveField(
            model_name='assetcheck',
            name='year',
        ),
        migrations.AddField(
            model_name='assetcheck',
            name='fiscal_year',
            field=models.PositiveIntegerField(default=2567, verbose_name='ปีงบประมาณ'),
        ),
        migrations.AlterField(
            model_name='issuingassetloan',
            name='month',
            field=models.PositiveIntegerField(default=8, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='orderassetloan',
            name='month',
            field=models.PositiveIntegerField(default=8, editable=False, verbose_name='เดือน'),
        ),
    ]
