# Generated by Django 4.2.16 on 2026-08-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_remove_assetcheck_month_remove_assetcheck_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcheck',
            name='check_image',
            field=models.ImageField(blank=True, null=True, upload_to='asset_checks/', verbose_name='รูปภาพการตรวจนับ'),
        ),
    ]
