# Generated by Django 4.2.16 on 2026-08-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_assetcheck_check_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public_check_enabled', models.BooleanField(default=False, verbose_name='เปิดสิทธิ์ให้ผู้ใช้งานทั่วไปตรวจนับครุภัณฑ์')),
                ('current_fiscal_year', models.CharField(blank=True, max_length=4, null=True, verbose_name='ปีงบประมาณปัจจุบันที่ตรวจนับ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ตั้งค่าระบบครุภัณฑ์',
                'verbose_name_plural': 'ตั้งค่าระบบครุภัณฑ์',
            },
        ),
    ]
