# Generated by Django 4.2.16 on 2026-08-18 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0024_assetsystemsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetsystemsetting',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='allowed_asset_checks', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้งานที่ได้รับสิทธิ์'),
        ),
    ]
