# Generated by Django 3.2 on 2024-04-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240419_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='workgroup',
            field=models.ForeignKey(max_length=150, on_delete=django.db.models.deletion.CASCADE, to='accounts.workgroup', verbose_name='กลุ่มงาน'),
        ),
    ]
