# Generated by Django 3.2 on 2024-05-27 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_workgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_executive',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ผู้บริหาร'),
        ),
    ]
