# Generated by Django 3.2 on 2024-06-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_myuser_is_executive'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-username'], 'verbose_name': 'สมาชิกผู้ใช้งาน User'},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='perfix',
            field=models.CharField(blank=True, choices=[('นาย', 'นาย'), ('นาง', 'นาง'), ('นางสาว', 'นางสาว'), ('ดร.', 'ดร.'), ('ผศ.ดร.', 'ผศ.ดร.'), ('รศ.ดร.', 'รศ.ดร.'), ('ศ.ดร.', 'ศ.ดร.'), ('อาจารย์', 'อาจารย์')], max_length=10, null=True, verbose_name='คำนำหน้า'),
        ),
    ]
