# Generated by Django 3.2 on 2024-07-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20240606_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์มือถือ'),
        ),
    ]
