# Generated by Django 3.2 on 2024-07-15 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-id'], 'verbose_name': 'สมาชิกผู้ใช้งาน User'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-workgroup'], 'verbose_name': 'ข้้อมูลสมาชิก'},
        ),
    ]
