# Generated by Django 3.2.6 on 2025-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_warehouse_manager',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ผู้จัดการสต๊อก'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ผู้จัดการ'),
        ),
    ]
