# Generated by Django 3.2.6 on 2025-02-03 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250203_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ผู้มีสิทธิ์อนุมัติ'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_warehouse_manager',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='ผู้จัดการคลัง'),
        ),
    ]
