# Generated by Django 3.2 on 2025-10-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20250203_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='image_users', verbose_name='รูปโปรไฟล์'),
        ),
    ]
