# Generated by Django 4.2.16 on 2026-08-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='รหัสระบบ')),
                ('title', models.CharField(max_length=200, verbose_name='ชื่อระบบ')),
                ('category', models.CharField(choices=[('research', 'งานวิจัย & นวัตกรรม'), ('incubator', 'บ่มเพาะธุรกิจ'), ('admin', 'บริหารจัดการ'), ('tools', 'ไอที & เครื่องมือ')], default='admin', max_length=20, verbose_name='หมวดหมู่')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='คำอธิบาย')),
                ('url', models.URLField(max_length=500, verbose_name='ลิงก์ URL')),
                ('icon', models.CharField(default='fa-link', max_length=50, verbose_name='ไอคอน Font Awesome')),
                ('icon_color', models.CharField(default='text-sky-600 bg-sky-50', max_length=100, verbose_name='สีไอคอน (CSS Classes)')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='รายการโปรด')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดงผล')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
            ],
            options={
                'verbose_name': 'ระบบ Portal',
                'verbose_name_plural': 'ระบบ Portal ทั้งหมด',
                'ordering': ['order', 'id'],
            },
        ),
    ]
