# Generated by Django 4.2.16 on 2026-08-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_portalapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalapp',
            name='app_image',
            field=models.ImageField(blank=True, null=True, upload_to='portal_apps/', verbose_name='รูปภาพระบบ'),
        ),
    ]
