# Generated by Django 3.2 on 2024-04-18 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cate', models.CharField(max_length=100, verbose_name='หมวดหมู่หลัก')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products', verbose_name='รูปภาพ')),
                ('product_id', models.CharField(max_length=50, unique=True, verbose_name='รหัสพัสดุ')),
                ('slug', models.SlugField(unique=True)),
                ('product_name', models.CharField(max_length=200, verbose_name='ชื่อรายการ')),
                ('description', models.TextField(verbose_name='คำอธิบาย')),
                ('quantityinstock', models.PositiveIntegerField(default=0, null=True, verbose_name='จำนวนที่มีในสต๊อก')),
                ('unitprice', models.PositiveIntegerField(verbose_name='ราคา/หน่วย')),
                ('unit', models.CharField(max_length=20, unique=True, verbose_name='หน่วย')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่มรายการ')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityreceived', models.PositiveIntegerField(default=0, null=True, verbose_name='จำนวนที่รับเข้า')),
                ('unitprice', models.PositiveIntegerField(null=True, verbose_name='ราคา/หน่วย')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่มรายการ')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receiving', to='shop.product', verbose_name='IDสินค้า')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supname', models.CharField(max_length=50, verbose_name='ชื่อบริษัท')),
                ('contactname', models.CharField(max_length=60, verbose_name='ชื่อผู้ติดต่อ')),
                ('phone', models.CharField(max_length=10, verbose_name='เบอร์โทรศัพท์')),
                ('address', models.CharField(max_length=255, verbose_name='ที่อยู่')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เพิ่มรายการ')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='TotalQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(verbose_name='รวมจำนวนที่รับเข้าทั้งหมด')),
                ('receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving', to='shop.receiving', verbose_name='IDสินค้า')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_sub', models.CharField(max_length=100, verbose_name='หมวดหมู่ย่อย')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='shop.category', verbose_name='หมวดหมู่หลัก')),
            ],
        ),
        migrations.AddField(
            model_name='receiving',
            name='suppliers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='shop.suppliers', verbose_name='IDซัพพลายเออร์'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subcategory', to='shop.subcategory', verbose_name='หมวดหมู่'),
        ),
    ]
