# Generated by Django 3.2 on 2024-04-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(max_length=20, verbose_name='หน่วย'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unitprice',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='ราคา/หน่วย'),
        ),
    ]
