# Generated by Django 3.2 on 2024-04-24 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20240422_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiving',
            old_name='Product',
            new_name='product',
        ),
    ]
