# Generated by Django 3.2 on 2024-04-25 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_product_receiving_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiving',
            name='quantityreceived',
        ),
        migrations.AddField(
            model_name='receiving',
            name='quantityreceive',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='จำนวนที่รับเข้า'),
        ),
    ]
