# Generated by Django 3.2 on 2024-04-25 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20240425_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiving',
            old_name='quantityreceive',
            new_name='quantityreceived',
        ),
    ]
