# Generated by Django 3.2 on 2024-04-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_quantityreceive_receiving_quantityreceived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalquantity',
            name='total_quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='รวมจำนวนที่รับเข้าทั้งหมด'),
        ),
    ]
