# Generated by Django 3.2 on 2024-05-02 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_totalquantity_total_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product', verbose_name='IDสินค้า')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
