# Generated by Django 3.2 on 2024-05-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_total_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_quantity',
            old_name='total_quantity',
            new_name='totalquantity',
        ),
    ]
