# Generated by Django 3.2 on 2024-05-02 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_total_quantity_total_quantity_totalquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='quantityreceived',
            field=models.PositiveIntegerField(null=True, verbose_name='จำนวนที่รับเข้า'),
        ),
    ]
