# Generated by Django 3.2 on 2024-05-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_receiving_quantityreceived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='receiving',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='จำนวนคงเหลือ'),
        ),
    ]
