# Generated by Django 3.2 on 2024-05-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20240507_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='จำนวนคงเหลือ'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='quantityreceived',
            field=models.PositiveIntegerField(null=True, verbose_name='จำนวนที่รับเข้า'),
        ),
    ]
