# Generated by Django 3.2 on 2024-05-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20240507_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='quantity',
            field=models.PositiveIntegerField(max_length=10, null=True, verbose_name='จำนวนคงเหลือ'),
        ),
    ]
