# Generated by Django 3.2 on 2024-05-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_receiving_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='quantity',
            field=models.PositiveIntegerField(null=True, verbose_name='จำนวนคงเหลือ'),
        ),
    ]
