# Generated by Django 3.2 on 2024-06-14 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดตข้อมูล'),
        ),
    ]
