# Generated by Django 3.2 on 2024-06-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_receiving_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดตข้อมูล'),
        ),
    ]
