# Generated by Django 3.2 on 2024-06-18 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_product_date_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='เดือน')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='ปี')),
                ('end_of_month_balance', models.PositiveIntegerField(blank=True, null=True, verbose_name='จำนวนคงเหลือ')),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stock_records', to='shop.product', verbose_name='IDสินค้า')),
            ],
        ),
    ]
