# Generated by Django 3.2 on 2024-07-01 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20240624_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='unitprice',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ราคา/หน่วย'),
        ),
    ]
