# Generated by Django 3.2 on 2024-07-02 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_receiving_unitprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unitprice',
        ),
    ]
