# Generated by Django 3.2 on 2024-07-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_monthlystockrecord_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่รับเข้า'),
        ),
    ]
