# Generated by Django 3.2 on 2024-08-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_receiving_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='taxnumber',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='เลขที่ประจำตัวผู้เสียภาษี'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='month',
            field=models.PositiveIntegerField(default=8, editable=False, verbose_name='เดือนที่รับเข้า'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='เบอร์โทรศัพท์'),
        ),
    ]
