# Generated by Django 3.2 on 2024-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20240819_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='receives', verbose_name='ไฟล์เอกสารแนบ'),
        ),
    ]
