# Generated by Django 3.2 on 2024-09-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20240906_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiving',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='หมายเหตุ'),
        ),
    ]
