# Generated by Django 3.2 on 2024-09-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_receiving_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('product_id',)},
        ),
        migrations.AlterField(
            model_name='receiving',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='หมายเหตุ'),
        ),
    ]
