# Generated by Django 3.2 on 2024-10-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_auto_20240924_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='month',
            field=models.PositiveIntegerField(default=10, editable=False, verbose_name='เดือนที่รับเข้า'),
        ),
    ]
