# Generated by Django 3.2 on 2024-11-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_receiving_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='month',
            field=models.PositiveIntegerField(default=11, editable=False, verbose_name='เดือนที่รับเข้า'),
        ),
    ]
