# Generated by Django 3.2.6 on 2025-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_auto_20250124_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='month',
            field=models.PositiveIntegerField(default=2, editable=False, verbose_name='เดือนที่รับเข้า'),
        ),
    ]
