# Generated by Django 3.2.6 on 2025-07-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_alter_receiving_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='month',
            field=models.PositiveIntegerField(default=7, editable=False, verbose_name='เดือนที่รับเข้า'),
        ),
    ]
