# Generated by Django 4.2.26 on 2025-11-26 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_alter_receiving_month'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='receiving',
            name='month',
            field=models.PositiveIntegerField(default=11, editable=False, verbose_name='เดือนที่รับเข้า'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='unitprice',
            field=models.DecimalField(decimal_places=10, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ราคา/หน่วย'),
        ),
    ]
