# Generated by Django 4.2.26 on 2025-11-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_product_options_alter_receiving_month_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlystockrecord',
            options={'verbose_name': 'บันทึกสต็อกรายเดือน', 'verbose_name_plural': 'บันทึกสต็อกรายเดือน'},
        ),
        migrations.AlterField(
            model_name='monthlystockrecord',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='monthlystockrecord',
            name='total_price',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=20, verbose_name='ราคารวม'),
        ),
        migrations.AlterField(
            model_name='monthlystockrecord',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ปี'),
        ),
        migrations.AlterUniqueTogether(
            name='monthlystockrecord',
            unique_together={('product', 'month', 'year')},
        ),
    ]
