# Generated by Django 4.2.26 on 2026-01-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_alter_monthlystockrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active_selling',
            field=models.BooleanField(default=True, verbose_name='เปิดขายปกติ'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='month',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='เดือนที่รับเข้า'),
        ),
        migrations.AlterField(
            model_name='receiving',
            name='year',
            field=models.PositiveIntegerField(default=2026, editable=False, verbose_name='ปีที่รับเข้า'),
        ),
    ]
