# Generated by Django 4.2.16 on 2026-08-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_product_is_active_selling_alter_receiving_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiving',
            name='month',
            field=models.PositiveIntegerField(default=8, editable=False, verbose_name='เดือนที่รับเข้า'),
        ),
    ]
