# Generated by Django 3.2 on 2024-04-18 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ทำรายการ')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดทออเดอร์')),
                ('approve', models.BooleanField(default=False, verbose_name='อนุมัติ')),
                ('refuse', models.BooleanField(default=False, verbose_name='ปฏิเสธ')),
                ('date_receive', models.DateTimeField(blank=True, null=True, verbose_name='วันที่จ่ายพัสดุ')),
                ('other', models.CharField(blank=True, max_length=50, null=True, verbose_name='หมายเหตุ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ใช้ID')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Issuing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='ราคา')),
                ('quantity', models.SmallIntegerField(verbose_name='จำนวน')),
                ('datecreated', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ทำรายการ')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issuing', to='orders.order', verbose_name='ออเดอร์ที่')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.product', verbose_name='สินค้า')),
            ],
        ),
    ]
