# Generated by Django 3.2 on 2024-04-19 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_issuing_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuing',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='ออเดอร์ที่'),
        ),
    ]
