# Generated by Django 3.2 on 2024-04-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_issuing_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approve',
            field=models.BooleanField(blank=True, null=True, verbose_name='อนุมัติ'),
        ),
    ]
