# Generated by Django 3.2 on 2024-05-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='approve',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refuse',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='สถานะออเดอร์'),
        ),
    ]
