# Generated by Django 3.2 on 2024-06-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_issuing_receiving'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuing',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='มูลค่ารวม'),
        ),
    ]
