# Generated by Django 3.2 on 2024-06-10 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_issuing_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuing',
            name='total_cost',
        ),
    ]
