# Generated by Django 3.2 on 2024-06-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_remove_issuing_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuing',
            name='month',
            field=models.PositiveIntegerField(default=6, editable=False, verbose_name='เดือน'),
        ),
        migrations.AddField(
            model_name='issuing',
            name='year',
            field=models.PositiveIntegerField(default=2024, editable=False, verbose_name='ปี'),
        ),
    ]
