# Generated by Django 3.2 on 2024-07-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20240627_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuing',
            name='month',
            field=models.PositiveIntegerField(default=7, editable=False, verbose_name='เดือน'),
        ),
    ]
