# Generated by Django 3.2 on 2024-07-01 03:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_issuing_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ราคา'),
        ),
    ]
