# Generated by Django 3.2 on 2024-07-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_issuing_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='month',
            field=models.PositiveIntegerField(default=7, editable=False, verbose_name='เดือน'),
        ),
        migrations.AddField(
            model_name='order',
            name='year',
            field=models.PositiveIntegerField(default=2024, editable=False, verbose_name='ปี'),
        ),
    ]
