# Generated by Django 3.2 on 2024-07-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20240702_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='ยืนยันรับพัสดุ'),
        ),
        migrations.AddField(
            model_name='order',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='วันที่ได้รับพัสดุ'),
        ),
        migrations.AddField(
            model_name='order',
            name='name_sign',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อผู้รับวัสดุ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_receive',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่นัดรับพัสดุ'),
        ),
    ]
