# Generated by Django 3.2 on 2024-07-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20240716_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_received',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='วันที่ได้รับพัสดุ'),
        ),
    ]
