# Generated by Django 3.2 on 2024-07-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_alter_order_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_item',
            field=models.BooleanField(default=False, verbose_name='ยืนยันจ่ายวัสดุ'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_received',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ได้รับพัสดุ'),
        ),
    ]
