# Generated by Django 3.2 on 2024-08-19 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20240819_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuing',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='หมายเหตุ'),
        ),
    ]
