# Generated by Django 3.2 on 2024-10-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20240924_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuing',
            name='month',
            field=models.PositiveIntegerField(default=10, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.PositiveIntegerField(default=10, editable=False, verbose_name='เดือน'),
        ),
    ]
