# Generated by Django 3.2 on 2024-11-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20241002_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name_pay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อผู้รับวัสดุ'),
        ),
        migrations.AddField(
            model_name='order',
            name='surname_pay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='นามสกุลผู้รับวัสดุ'),
        ),
        migrations.AlterField(
            model_name='issuing',
            name='month',
            field=models.PositiveIntegerField(default=11, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.PositiveIntegerField(default=11, editable=False, verbose_name='เดือน'),
        ),
    ]
