# Generated by Django 3.2 on 2024-11-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20241104_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name_pay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อผู้จ่าย'),
        ),
        migrations.AlterField(
            model_name='order',
            name='surname_pay',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='นามสกุลผู้จ่าย'),
        ),
    ]
