# Generated by Django 3.2 on 2024-11-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20241104_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvereport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_report', models.CharField(blank=True, max_length=50, null=True, verbose_name='รายงานการเบิกวัสดุประจำเดือน')),
                ('name_sign1', models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อ ผู้สำรวจ1')),
                ('surname_sign1', models.CharField(blank=True, max_length=50, null=True, verbose_name='นามสกุล ผู้สำรวจ1')),
                ('position1', models.CharField(blank=True, max_length=50, null=True, verbose_name='ตำแหน่ง1')),
                ('name_sign2', models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อ ผู้สำรวจ2')),
                ('surname_sign2', models.CharField(blank=True, max_length=50, null=True, verbose_name='นามสกุล ผู้สำรวจ2')),
                ('position2', models.CharField(blank=True, max_length=50, null=True, verbose_name='ตำแหน่ง2')),
                ('approve', models.BooleanField(default=False, verbose_name='อนุมัติรายงาน')),
                ('name_approve', models.CharField(blank=True, max_length=50, null=True, verbose_name='ชื่อ ผู้ตรวจสอบ')),
                ('surname_approve', models.CharField(blank=True, max_length=50, null=True, verbose_name='นามสกุล ผู้ตรวจสอบ')),
                ('position3', models.CharField(blank=True, max_length=50, null=True, verbose_name='ตำแหน่ง3')),
                ('other', models.CharField(blank=True, max_length=500, null=True, verbose_name='หมายเหตุ')),
                ('month', models.PositiveIntegerField(default=11, editable=False, verbose_name='เดือน')),
                ('year', models.PositiveIntegerField(default=2024, editable=False, verbose_name='ปี')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ทำรายการ')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='วันที่อัพเดท')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
