# Generated by Django 3.2.6 on 2025-01-24 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0035_auto_20250124_1442'),
        ('orders', '0028_approvereport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvereport',
            name='month',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='approvereport',
            name='year',
            field=models.PositiveIntegerField(default=2025, editable=False, verbose_name='ปี'),
        ),
        migrations.AlterField(
            model_name='issuing',
            name='month',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='issuing',
            name='year',
            field=models.PositiveIntegerField(default=2025, editable=False, verbose_name='ปี'),
        ),
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.PositiveIntegerField(default=1, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.PositiveIntegerField(default=2025, editable=False, verbose_name='ปี'),
        ),
        migrations.CreateModel(
            name='OutOfStockNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.PositiveIntegerField(verbose_name='จำนวนที่ต้องการเพิ่ม')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่แจ้ง')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='รับทราบ')),
                ('restocked', models.BooleanField(default=False, verbose_name='เติมสต๊อกแล้ว')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='shop.product', verbose_name='วัสดุ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แจ้ง')),
            ],
            options={
                'verbose_name': 'การแจ้งวัสดุหมด',
                'verbose_name_plural': 'การแจ้งวัสดุหมด',
                'ordering': ['-date_created'],
            },
        ),
    ]
