# Generated by Django 3.2.6 on 2025-01-24 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20250124_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Approvereport',
        ),
    ]
