# Generated by Django 3.2.6 on 2025-01-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_delete_approvereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='outofstocknotification',
            name='acknowledged_note',
            field=models.TextField(blank=True, null=True, verbose_name='โน๊ตจากเจ้าหน้าที่'),
        ),
    ]
