# Generated by Django 3.2.6 on 2025-02-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_outofstocknotification_acknowledged_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuing',
            name='month',
            field=models.PositiveIntegerField(default=2, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.PositiveIntegerField(default=2, editable=False, verbose_name='เดือน'),
        ),
    ]
