# Generated by Django 3.2.6 on 2025-07-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20250203_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่อนุมัติ'),
        ),
        migrations.AlterField(
            model_name='issuing',
            name='month',
            field=models.PositiveIntegerField(default=7, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.PositiveIntegerField(default=7, editable=False, verbose_name='เดือน'),
        ),
    ]
