# Generated by Django 3.2.6 on 2025-07-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20250715_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_pay',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่จ่ายพัสดุ'),
        ),
    ]
