# Generated by Django 3.2 on 2025-10-29 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20250909_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, unique=True, verbose_name='รหัสออเดอร์'),
        ),
        migrations.AddField(
            model_name='order',
            name='running_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='เลขลำดับ'),
        ),
        migrations.AlterField(
            model_name='issuing',
            name='month',
            field=models.PositiveIntegerField(default=10, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.PositiveIntegerField(default=10, editable=False, verbose_name='เดือน'),
        ),
    ]
