# Generated by Django 4.2.26 on 2025-11-26 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_alter_issuing_month_alter_order_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuing',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=20, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='ราคา'),
        ),
        migrations.AlterField(
            model_name='issuing',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='จำนวน'),
        ),
    ]
