# Generated by Django 4.2.16 on 2026-08-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_alter_issuing_price_alter_issuing_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuing',
            name='month',
            field=models.PositiveIntegerField(default=8, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='issuing',
            name='year',
            field=models.PositiveIntegerField(default=2026, editable=False, verbose_name='ปี'),
        ),
        migrations.AlterField(
            model_name='order',
            name='month',
            field=models.PositiveIntegerField(default=8, editable=False, verbose_name='เดือน'),
        ),
        migrations.AlterField(
            model_name='order',
            name='year',
            field=models.PositiveIntegerField(default=2026, editable=False, verbose_name='ปี'),
        ),
    ]
